Extremely Casual Game Organizer/MvcPresentation/Controllers/TournamentsController.cs
using DataObjects;
using LogicLayer;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPresentation.Controllers
{
    public class TournamentsController : Controller
    {
        TournamentManager tournamentManager = new TournamentManager();
        TeamManager teamManager = new TeamManager();
        private List<Tournament> tournaments = null;
        private List<TournamentTeam> tournamentTeams = null;
        private List<TournamentTeamGame> tournamentGames = null;
        private List<Team> tournamentTeamname = new List<Team>();
        private List<TeamSport> teams = new List<TeamSport>();
        private MemberManager _memberManager = new MemberManager();
        private List<TournamentGenerateGames> games = new List<TournamentGenerateGames>();

        List<string> sports = new List<string>();
        List<int> sportIds = new List<int>();
        int memberID = 0;

        Tournament tournament = new Tournament();

        // GET: Tournament
        public ActionResult AllTournaments()
        {
            try
            {
                tournaments = tournamentManager.GetTournaments();
            }catch(Exception ex)
            {
                ViewBag.Message = ex;
            }

            return View(tournaments);
        }

        // GET: Tournament
        public ActionResult MemberTournaments()
        {
            try
            {
                memberID = GetUserID(User.Identity.Name);
                tournaments = tournamentManager.GetTournaments();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex;
            }
            ViewBag.Me = memberID;
            return View(tournaments);
        }
        

        // GET: Tournament Detail
        public ActionResult Details(int id, int? type, int? error)
        {
            try
            {

                memberID = GetUserID(User.Identity.Name);
                getSports();
                ViewBag.sports = sports;
                tournaments = tournamentManager.GetTournaments();
                tournament = tournaments.Where(b => b.TournamentID == id).First();
                tournamentTeams = tournamentManager.GetTournamentTeamByID(id);
                tournamentGames = tournamentManager.SelectTournamentTeamAndGame(id);

                getTournamentTeamName(tournamentTeams);
                getTeamGame(tournamentGames);

                ViewBag.TournamentTeams = tournamentTeamname;
                ViewBag.TournamentGames = games;
                ViewBag.NbreTeam = tournamentTeams.Count;
                ViewBag.NbreGame = tournamentGames.Count/2;
                ViewBag.Type = type;

                ViewBag.TeamError = (string)TempData["TeamError"];
                
                ViewBag.TeamError = TempData["TeamError"];

                ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                var user = userManager.FindById(User.Identity.GetUserId());
                if(user != null){
                    if (user.MemberID != tournament.MemberID)
                    {
                        ViewBag.NotOwner = "hidden";
                    }
                    else
                    {
                        ViewBag.IsOwner = "hidden";
                    }
                }
                else
                {
                    ViewBag.NotOwner = "hidden";
                    ViewBag.IsOwner = "hidden";
                }


                if (tournament != null)
                {
                    if (tournament.Gender == true) ViewBag.Gender = "Male";
                    else if (tournament.Gender == false) ViewBag.Gender = "Female";
                    else ViewBag.Gender = "Not specify";
                    ViewBag.Sportname = getSportName(tournament.SportID);
                }

                if (error == 2)
                {
                    ViewBag.Message = "Tournament updated successfully!";
                    ViewBag.Error = false;
                }
                else if(error == 1)
                {
                    ViewBag.Message = "An error has occurred!";
                    ViewBag.Error = true;
                }
                else
                {
                    ViewBag.Message = null;
                    ViewBag.Error = false;
                }

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }


            ViewBag.TournamentID = id;
            ViewBag.Me = memberID;
            return View(tournament);
        }

        // GET: Tournament Create
        public ActionResult CreateTournament()
        {
            try
            {
                getSports();
                ViewBag.sports = sports;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }

            return View();
        }

        // GET: Tournament Create
        [HttpPost]
        public ActionResult CreateTournament(string name, string sportname, bool? gender, string description)
        {
            try
            {
                getSports();
                ViewBag.sports = sports;

                memberID = GetUserID(User.Identity.Name);
                int sport_id = 0;
                for (int item = 0; item < sports.Count; item++)
                {
                    if (sports[item] == sportname)
                    {
                        sport_id = sportIds[item];
                    }
                }

                Tournament tournament = new Tournament()
                {
                    Name = name,
                    SportID = sport_id,
                    Gender = gender,
                    Description = description,
                    MemberID = memberID
                };

                bool result = tournamentManager.CreateTournament(tournament);
                if (result == true)
                {
                    ViewBag.Error = false;
                    ViewBag.Message = "Tournament Created successfully!";
                }
                else
                {
                    ViewBag.Error = true;
                    ViewBag.Message = "An error has occurred!";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                ViewBag.Error = true;
            }

            return View();
        }

        // GET: Tournament Delete
        public ActionResult Delete(int id)
        {

            int error = 0;
            string message = "";

            try
            {
                getSports();
                ViewBag.sports = sports;

                memberID = GetUserID(User.Identity.Name);

                bool result = tournamentManager.DeleteTournament(memberID, id);
                if (result == true)
                {
                    message = "Tournament deleted successfully!";
                    error = 2;
                }
                else
                {
                    message = "An error has occurred!";
                    error = 1;
                }
            }
            catch (Exception ex)
            {
                ViewBag.MessageError = ex.Message;
            }

            ViewBag.Message = message;
            ViewBag.Error = error;

            return RedirectToAction("Details", new { 
                id = id,
                error = error
            });
        }

        // GET: Tournament Delete
        public ActionResult Activate(int id)
        {

            int error = 0;
            string message = "";

            try
            {
                getSports();
                ViewBag.sports = sports;

                memberID = GetUserID(User.Identity.Name);

                bool result = tournamentManager.ActivateTournament(memberID, id);
                if (result == true)
                {
                    message = "Tournament activated successfully!";
                    error = 2;
                }
                else
                {
                    message = "An error has occurred!";
                    error = 1;
                }
            }
            catch (Exception ex)
            {
                ViewBag.MessageError = ex.Message;
            }

            ViewBag.Message = message;
            ViewBag.Error = error;

            return RedirectToAction("Details", new
            {
                id = id,
                error = error
            });
        }

        // GET: Tournament Edit
        public ActionResult EditTournaments(int id)
        {
            try
            {
                getSports();
                ViewBag.sports = sports;

                tournaments = tournamentManager.GetTournaments();
                tournament = tournaments.Where(b => b.TournamentID == id).First();

                string sportname = "";
                for (int item = 0; item < sportIds.Count; item++)
                {
                    if (sportIds[item] == tournament.SportID)
                    {
                        sportname = sports[item];
                    }
                }

                ViewBag.sportname = sportname;

            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View(tournament);
        }

        [HttpPost]
        public ActionResult EditTournaments(int id, string name, string sportname, bool? gender, string description)
        {

            memberID = GetUserID(User.Identity.Name);
            Tournament _tournament = new Tournament()
            {
                TournamentID = id,
                Name = name,
                Gender = gender,

Extremely Casual Game Organizer/MvcPresentation/Views/Tournaments/AllTournaments.cshtml
@model IEnumerable<DataObjects.Tournament>

@{
    ViewBag.Title = "AllTournaments";
}


<div class="row">

    <div class="col-12 bg-primary" style="padding:30px 30px 50px; margin-bottom:30px">
        <h2>Tournaments</h2>
        <a class="btn btn-success btn-lg" href="~/Tournaments/CreateTournament">Create a tournament</a>
    </div>

    <div class="col-12" style="padding:15px 30px 30px; margin-bottom:30px">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-3" style="padding:15px 15px 5px">
                    <a href="~/Tournaments/Details/@Html.DisplayFor(modelItem => item.TournamentID)">
                        <div style="box-shadow:0px 0px 0px 1px #D0D0D0;">
                            <div style="background-color:white; color:black;
                        padding:30px 0px; font-size:1.3em; min-height:120px; font-weight:bold;
                        display:flex; align-items:center; justify-content:center; text-align:center;padding:10px">
                                @Html.DisplayFor(modelItem => item.Name)
                            </div>

                            @if (item.Active)
                            {
                                <div style="text-align:center; color:green;padding-bottom:10px">
                                    <h4>Active</h4>
                                </div>
                                <div style="background-color:#F4F4F4;
                                    padding:20px 0px; font-size:1.3em; min-height:40px;
                                    display:flex; align-items:center; justify-content:center">
                                    <span class="btn btn-success">Open</span>
                                </div>
                            }
                            else
                            {
                                <div style="text-align:center; color:red;padding-bottom:10px">
                                    <h4>Inactive</h4>
                                </div>
                                <div style="background-color:#F4F4F4;
                                    padding:20px 0px; font-size:1.3em; min-height:40px;
                                    display:flex; align-items:center; justify-content:center">
                                    <span class="btn btn-danger">Open</span>
                                </div>
                            }

                        </div>
                    </a>
                </div>
            }

        </div>
    </div>

</div>

Extremely Casual Game Organizer/MvcPresentation/Views/Tournaments/CreateTournament.cshtml
@model DataObjects.Tournament

@{
    ViewBag.Title = "CreateTournament";
}

@try
{
<div class="row">
    <div class="col-12" style="padding:15px 30px 30px; margin:30px 0px">
        <h2>Create a Tournament</h2>
        <a class="btn btn-success btn-lg" href="~/Tournaments/AllTournaments">View All tournaments</a>

        <div style="margin-top:10px">
            @if (@ViewBag.Message != null)
            {
                if (ViewBag.Error == false)
                {
                    <div class="alert alert-success">
                        <h5>@ViewBag.Message</h5>
                    </div>
                }
                else
                {
                    <div class="alert alert-danger">
                        <h5>@ViewBag.Message</h5>
                    </div>
                }
            }
        </div>

    </div>
    <div class="col-12 bg-primary" style="padding:30px; margin-bottom:30px; background-color:#F0F0F0">
        <div class="row" style="display:flex; justify-content:center;">

            <div class="col-md-5" style="padding:50px 20px 30px; background-color:white;color:black">
                <h2 style="text-align:center">Tournament</h2>

                <form class="form" method="post" action="~/Tournaments/CreateTournament">

                    @Html.AntiForgeryToken()
                    <div style="padding:5px 0px">
                        <div style="padding:0px 20px 0px">
                            <h4 for="description">Name:</h4>
                        </div>
                        <div style="padding:10px 20px">
                            <input name="name" type="text" class="form-control" style="width: 100%; max-width: 100%;" />
                        </div>
                    </div>

                    <div style="padding:5px 0px">
                        <div style="padding:0px 20px 0px">
                            <h4 for="description">Sport:</h4>
                        </div>
                        <div style="padding:10px 20px">
                            <select name="sportname" class="form-control" style="width: 100%; max-width: 100%;">
                                <option></option>
                                @foreach (var item in ViewBag.sports)
                                {
                                    <option value="@Html.DisplayFor(modelitem => item)">
                                        @Html.DisplayFor(modelitem => item)
                                    </option>
                                }
                            </select>
                        </div>
                    </div>

                    <div style="padding:5px 0px">
                        <div style="padding:0px 20px 0px">
                            <h4 for="description">Gender:</h4>
                        </div>
                        <div style="padding:10px 20px">
                            <select name="gender" class="form-control" style="width: 100%; max-width: 100%;">
                                <option></option>
                                <option value="true">Male</option>
                                <option value="false">Female</option>
                            </select>
                        </div>
                    </div>

                    <div style="padding:5px 0px">
                        <div style="padding:0px 20px 0px">
                            <h4 for="description">Description:</h4>
                        </div>
                        <div style="padding:10px 20px">
                            <textarea class="form-control" rows="5" name="description" style="width: 100%; max-width: 100%;"></textarea>
                        </div>
                    </div>

                    <div style="display:flex; justify-content:center">
                        <div class="col-md-5" style="padding:15px 0px">
                            <input type="submit" class="btn btn-block btn-success" value="Submit" />
                        </div>
                    </div>

                </form>

            </div>

        </div>

    </div>
</div>

}
catch (Exception)
{
    <div class="alert alert-danger">
        An error has occurred!
    </div>
}

Extremely Casual Game Organizer/MvcPresentation/Views/Tournaments/Details.cshtml
@model DataObjects.Tournament

@{
    ViewBag.Title = "Details";
}


    <div class="row">

        <div class="col-12" style="padding:30px 30px;">
            <h3 class="alert-danger">@ViewBag.TeamError</h3>
            <h3>Tournament Details of:</h3>
            <span style="font-weight:bold; font-size:3.2em">@Model.Name</span>
        </div>

        <div style="margin-top:10px">
            @if (@ViewBag.Message != null)
            {
                if (ViewBag.Error == false)
                {
                    <div class="alert alert-success">
                        <h5>@ViewBag.Message</h5>
                    </div>
                }
                else
                {
                    <div class="alert alert-danger">
                        <h5>@ViewBag.Message</h5>
                    </div>
                }
            }
        </div>

        <div class="col-12">

            <div class="row">

                <div class="col-md-12">

                    <div class="row">

                        <div class="col-md-3" style="padding:25px">
                            <a href="~/Tournaments/Details/@ViewBag.TournamentID" class="bg-info noDecoration" style=" display: flex; flex-direction: column;
                            align-items: center; padding: 5px 0px; color:black;
                            height: 150px; justify-content: center">
                                <h1 style="text-align:center">
                                    <span style="font-size:.8em">Overview</span>
                                </h1>
                            </a>
                        </div>

                        <div class="col-md-3" style="padding:25px">
                            <a href="~/Tournaments/Details?id=@ViewBag.TournamentID&&type=1" class="bg-info noDecoration" style="display:flex;flex-direction:column;
                            align-items:center;padding:5px 0px; height:150px; color:black;">
                                <h1 style="text-align:center">
                                    <span style="font-size:1.7em">@ViewBag.NbreTeam</span><br />
                                    @if (ViewBag.NbreTeam > 1)
                                    {
                                        <span style="font-size:.8em">Teams</span>
                                    }
                                    else
                                    {
                                        <span style="font-size:.8em">Team</span>
                                    }
                                </h1>
                            </a>
                        </div>

                        <div class="col-md-3" style="padding:25px">
                            <a href="~/Tournaments/Details?id=@ViewBag.TournamentID&&type=2" class="bg-info noDecoration" style="display:flex;flex-direction:column;
                            align-items:center;padding:5px 0px; height:150px; color:black;">
                                <h1 style="text-align:center">
                                    <span style="font-size:1.7em">@ViewBag.NbreGame</span><br />
                                    @if (ViewBag.NbreGame > 1)
                                    {
                                        <span style="font-size:.8em">Games</span>
                                    }
                                    else
                                    {
                                        <span style="font-size:.8em">Game</span>
                                    }
                                </h1>
                            </a>
                        </div>

                        @if (@ViewBag.Type == 1)
                        {
                            @*Teams*@
                            <div class="col-md-10" style="margin: 20px 15px;
                            padding:25px 50px; background-color: #F0F0F0">
                                @if (ViewBag.NbreTeam > 1)
                                {
                                    <h1 style="text-align:left; color:black">Teams</h1>
                                }
                                else
                                {
                                    <h1 style="text-align:left; color:black">Team</h1>
                                }

                            <div style="margin:30px 0px">
                                @foreach (var item in ViewBag.TournamentTeams)
                                {
                                    <a class="noDecoration" href=""
                                       style="display: flex; flex-direction: row; justify-content:start;
                                        align-items:center;padding:10px 20px; margin-top:5px; background-color:white">
                                        <div class="col-md-8" style="padding: 0px 20px">
                                            <p style="font-size:2em;color:black">
                                                @item.TeamName
                                            </p>
                                        </div>
                                        <div class="col-md-4" style="padding: 0px 20px">
                                            <span class="btn btn-success btn-lg">View Team</span>
                                        </div>
                                    </a>
                                }


                                @if (ViewBag.NbreTeam == 0)
                                {
                                    <div style="text-align:center; margin-top:50px">
                                        <h3>-- Empty -- </h3>
                                    </div>
                                }


                                @if (Model.MemberID == ViewBag.Me)
                                {
                                    <div style="text-align:center; margin-top:50px">
                                        <a href="~/Tournaments/TournamentTeam?id=@ViewBag.TournamentID&&sport_id=@Model.SportID" class="btn btn-primary btn-lg" style="padding:10px 30px; margin:0px 5px">Manage Teams</a>
                                    </div>
                                }
                            </div>

                            </div>
                        }
                        else if (@ViewBag.Type == 2)
                        {

                            @*Games*@
                    <div class="col-md-10" style="margin: 20px 15px;
                            padding:25px 50px; background-color: #F0F0F0">
                        @if (ViewBag.NbreGame > 1)
                        {
                            <h1 style="text-align:left; color:black">Games</h1>
                        }
                        else
                        {
                            <h1 style="text-align:left; color:black">Game</h1>
                        }

                        <div style="margin:30px 0px">
                            @foreach (var item in ViewBag.TournamentGames)
                            {
                                <a class="noDecoration" href=""
                                   style="display: flex;flex-direction: row;justify-content: start;
                                      align-items: center;padding: 10px 20px;margin-top: 5px;
                                      background-color: white">
                                    <div class="col-md-12" style="padding: 0px 20px">
                                        <p style="font-size:1.8em;color:black; text-align:left">
                                            @item.Content
                                        </p>
                                    </div>
                                </a>
                            }
                        </div>


                        @if (ViewBag.NbreGame == 0)
                        {
                            <div style="text-align:center; margin-top:50px">
                                <h3>-- Empty -- </h3>
                            </div>
                        }

                        @if (Model.MemberID == ViewBag.Me)
                        {
                            <div style="text-align:center; margin-top:50px">
                                <a href="" class="btn btn-primary btn-lg" style="padding:10px 30px; margin:0px 5px">Manage Games</a>
                            </div>
                        }


                    </div>
                        }
                        else
                        {
                            @*Overview*@
                            <div class="col-md-10" style="margin: 20px 15px;
                            padding:25px 50px; background-color: #F0F0F0">
                                <h1 style="text-align:left; color:black">Overview</h1>

                                <div style="margin:30px 0px; font-size:1.7em;">
                                    <table class="table table-hover table-responsive">
                                        <tr>
                                            <td>Name</td>
                                            <td>: @Model.Name</td>
                                        </tr>
                                        <tr>
                                            <td>Gender</td>
                                            <td>: @ViewBag.Gender</td>
                                        </tr>
                                        <tr>
                                            <td>Sport</td>
                                            <td>: @ViewBag.Sportname</td>
                                        </tr>
                                        <tr>
                                            <td>Active</td>
                                            @if (@Model.Active)
                                            {
                                                <td>: <span class="bg-success" style="padding:5px; font-weight:bold">Yes</span></td>
                                            }
                                            else
                                            {
                                                <td>: <span class="bg-danger" style="padding:5px; font-weight:bold">No</span></td>
                                            }
                                        </tr>
                                        <tr>
                                            <td>Description</td>
                                            <td>: @Model.Description</td>
                                        </tr>

                                    </table>

                                    <a href="@Url.Action("JoinRequests", "Tournaments", new { tournamentID = ViewBag.TournamentID })" class="btn btn-primary @ViewBag.NotOwner">Join Requests</a>
                                    <a href="@Url.Action("JoinTournament", "Tournaments", new { tournamentID = ViewBag.TournamentID })" class="btn btn-primary @ViewBag.IsOwner">Join Tournament</a>
                                    @if (Model.MemberID == ViewBag.Me)
                                    {
                                        <div style="text-align:right; margin-top:50px">
                                            <a href="~/Tournaments/EditTournaments/@ViewBag.TournamentID" class="btn btn-primary" style="padding:10px 30px; margin:0px 5px">Edit</a>
                                            @if (Model.Active == true)
                                            {
                                                <a href="~/Tournaments/Delete/@ViewBag.TournamentID" class="btn btn-danger" style="padding:10px 30px; margin:0px 5px">Deactivate</a>
                                            }
                                            else
                                            {
                                                <a href="~/Tournaments/Activate/@ViewBag.TournamentID" class="btn btn-success" style="padding:10px 30px; margin:0px 5px">Activate</a>
                                            }
                                        </div>
                                    }

                                </div>

                            </div>
                        }

                    </div>

                </div>

            </div>

        </div>

    </div>

Extremely Casual Game Organizer/MvcPresentation/Views/Tournaments/JoinRequests.cshtml
@model IEnumerable<DataObjects.TournamentRequest>

@{
    ViewBag.Title = "JoinRequests";
}

<h2>JoinRequests</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TeamID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Accept", "JoinRequests", new { tournamentID=item.TournamentID, teamID = item.TeamID, requestID = item.TournamentRequestID, acceptance = "Accept" }) |
            @Html.ActionLink("Deny", "JoinRequests", new { tournamentID=item.TournamentID, teamID = item.TeamID, requestID = item.TournamentRequestID, acceptance = "Deny" })
        </td>
    </tr>
}

</table>

Extremely Casual Game Organizer/MvcPresentation/Views/Tournaments/JoinTournament.cshtml
@model DataObjects.TournamentRequest

@{
    ViewBag.Title = "JoinTournament";
}

<h2>JoinTournament</h2>


<div class="container">
    <div class="row">
        <h3 class="danger">@ViewBag.Error</h3>
        <h2>Which team would you like to join this tournament with?</h2>
    </div>
    
    <div class="row">
        <form method="post" action="@Url.Action("JoinTournament","Tournaments")">

            @Html.HiddenFor(model => model.TournamentID)

            <select class="col-md-6" name="TeamID">
                @foreach (var item in ViewBag.Teams)
                {
                    <option value=@item.TeamID>@item.TeamName</option>
                }
            </select>
            <br />
            <input type="submit" value="Submit" class="btn btn-success">

        </form>
    </div>

    <div class="row">

    </div>
</div>