Extremely Casual Game Organizer/MvcPresentation/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataObjects;
using System.Data;
using LogicLayer;

namespace MvcPresentation.Controllers
{
    public class GamesController : Controller
    {
        MasterManager _masterManager;
        public GamesController()
        {
            _masterManager = new MasterManager();
        }
        // GET: Games
        /// <summary>
        /// Created By: Jacob Lindauer 
        /// Date: 04/20/2023
        /// 
        /// View All Games
        /// </summary>
        /// <returns></returns>
        public ActionResult AllGames()
        {
            try
            {
                DataTable gameList = _masterManager.GameManager.ViewAllGames();

                return View(gameList);
            }
            catch (Exception ex)
            {

                ViewBag.ErrorMessage = ex.Message;
                return View("Error");
            }
        }

        // GET: Games/Details/5
        /// <summary>
        /// Created By: Jacob Lindauer 
        /// Date: 04/20/2023
        /// 
        /// View game details
        /// </summary>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            try
            {
                DataRow details = _masterManager.GameManager.ViewGameDetails(id);

                // Load Team Data and Rosters. Should only be 2 results per game
                var teams = _masterManager.GameRosterManager.RetrieveGameRoster(id).Select(x => x.TeamID).Distinct();

                Team team1 = _masterManager.TeamManager.RetrieveTeamByTeamID(teams.First());
                Team team2 = _masterManager.TeamManager.RetrieveTeamByTeamID(teams.Last());

                var team1Roster = from player in _masterManager.GameRosterManager.RetrieveGameRoster(id) where player.TeamID.Equals(team1.TeamID) select player;

                var team2Roster = from player in _masterManager.GameRosterManager.RetrieveGameRoster(id) where player.TeamID.Equals(team2.TeamID) select player;

                var gameScores = _masterManager.GameManager.RetreiveScoresByGameID(id);

                ViewBag.Team1 = team1;
                ViewBag.Team2 = team2;
                ViewBag.Team1Roster = team1Roster;
                ViewBag.Team2Roster = team2Roster;

                Score team1Score = (from score in gameScores where score.TeamID == team1.TeamID select score).First();
                Score team2Score = (from score in gameScores where score.TeamID == team2.TeamID select score).First();

                if (team1Score != null && team2Score != null)
                {
                    if (team1Score.TeamScore % 1 == 0 || team2Score.TeamScore % 1 == 0)
                    {
                        if (team1Score.TeamScore % 1 == 0)
                        {
                            ViewBag.Team1Score = Convert.ToInt32(team1Score.TeamScore);
                        }
                        if (team2Score.TeamScore % 1 == 0)
                        {
                            ViewBag.Team2Score = Convert.ToInt32(team2Score.TeamScore);
                        }
                    }
                    else
                    {
                        ViewBag.Team1Score = team1Score.TeamScore;
                        ViewBag.Team2Score = team2Score.TeamScore;
                    }
                }
                // Placeholder until implemented

                return View(details);
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View("Error");
            }
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Games/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Games/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Extremely Casual Game Organizer/MvcPresentation/Controllers/MessagesController.cs
using DataObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCPresentation.Controllers
{
    public class MessagesController : Controller
    {
        MessageManager _messageManager = new MessageManager();
        private MemberManager _memberManager = new MemberManager();
        List<Member> members = new List<Member>();
        List<Message> messages = new List<Message>();
        Member otherMember = new Member();
        private Member _member;

        // GET: Message

        [Authorize]
        public ActionResult Index(string email)
        {
            try
            {
                int member_id = GetUserID(User.Identity.Name);
                otherMember = GetUserData(email);

                if (member_id > 0 && otherMember != null)
                {
                    messages = _messageManager.GetMessages(member_id, otherMember.MemberID);
                    ViewBag.Me = member_id;
                    ViewBag.Him = otherMember.MemberID;
                    ViewBag.Email = otherMember.Email;
                    ViewBag.MemberName = otherMember.FirstName + " " + otherMember.FamilyName;
                }
            }
            catch (Exception ex)
            {
                throw new ApplicationException("An Error occured! " + ex.Message);
            }

            if (messages != null)
            {
                foreach (Message line in messages)
                {
                    if (line.ProfilePhoto != null)
                    {
                        string imreBase64Data = Convert.ToBase64String(line.ProfilePhoto);
                        string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                        //Passing image data in viewbag to view
                        line.Photo = imgDataURL;
                    }
                }
            }
            return View(messages);
        }


        // GET: People I texted
        [Authorize]
        public ActionResult PeopleITexted()
        {
            try
            {
                int member_id = GetUserID(User.Identity.Name);
                if (member_id > 0)
                {
                    members = _messageManager.GetMembers(member_id);

                    ViewBag.Me = member_id;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ("An Error occured! " + ex.Message);
                return View("Error");
            }

            if (members != null)
            {
                foreach (Member line in members)
                {
                    if (line.ProfilePhoto != null)
                    {
                        string imreBase64Data = Convert.ToBase64String(line.ProfilePhoto);
                        string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                        //Passing image data in viewbag to view
                        line.Photo = imgDataURL;
                    }
                }
            }

            return View(members);
        }

        // GET: Send Message
        [Authorize]
        [HttpPost]
        public ActionResult Create(string message, int user_id, int other_user_id, string email)
        {
            try
            {
                Message _message = new Message()
                {
                    UserIdSender = user_id,
                    UserIdReceiver = other_user_id,
                    Date = DateTime.Now,
                    Important = true,
                    MessageText = message
                };

                int result = _messageManager.AddMessage(_message);
            }
            catch (Exception ex)
            {
                throw new ApplicationException("An Error occured! " + ex.Message);
            }

            return RedirectToAction("Index", new
            {
                email = email
            });
        }

        [HttpGet]
        [Authorize]
        public ActionResult AllMembers()
        {
            members = _memberManager.GetMembers();

            if (members != null)
            {
                foreach (Member line in members)
                {
                    if (line.ProfilePhoto != null)
                    {
                        string imreBase64Data = Convert.ToBase64String(line.ProfilePhoto);
                        string imgDataURL = string.Format("data:image/png;base64,{0}", imreBase64Data);
                        //Passing image data in viewbag to view
                        line.Photo = imgDataURL;
                    }
                }
            }

            return View(members);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AllMembers(string username)
        {
            if (username != null && username != "")
            {
                ViewBag.Message = "Search for: " + username;
                members = _memberManager.GetMemberByName(username);
            }
            return View(members);
        }


        // Get user info
        public Member GetUserData(string email)
        {
            try
            {
                _member = _memberManager.GetMemberByName(email).First();
            }
            catch (Exception ex)
            {
                throw new ApplicationException(ex.Message);
            }
            return _member;
        }


        // Get user info
        public Member GetUserInfo(string email)
        {
            try
            {
                _member = _memberManager.GetMemberByName(email).First();
            }
            catch (Exception ex)
            {
                throw new ApplicationException(ex.Message);
            }
            return _member;
        }


        public int GetUserID(string email)
        {
            try
            {
                _member = _memberManager.GetMemberByName(email).First();
            }
            catch (Exception ex)
            {
                throw new ApplicationException(ex.Message);
            }

            return _member.MemberID;
        }

    }
}

Extremely Casual Game Organizer/MvcPresentation/Controllers/TeamsController.cs
using DataObjects;
using LogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace MvcPresentation.Controllers
{
    public class TeamsController : Controller
    {
        TeamManager teamManager = new TeamManager();
        List<Team> teams = new List<Team>();
        List<string> sports = new List<string>();
        List<int> sportIds = new List<int>();


        // GET: Team
        public ActionResult Index()
        {
            return View();
        }

        // GET: Team
        /// <summary>
        // Heritier Otiom
        /// </summary>
        public ActionResult Details(int id)
        {
            teams = teamManager.RetrieveAllTeams();
            Team team = teams.Find(x => x.TeamID == id);
            return View(team);
        }

        // GET: Create Team
        /// <summary>
        // Heritier Otiom
        /// </summary>
        public ActionResult CreateTeam()
        {
            try
            {
                getSports();
                ViewBag.sports = sports;
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
            return View();
        }

        /// <summary>
        // Heritier Otiom
        /// </summary>
        [HttpPost]
        public ActionResult CreateTeam(string TeamName, bool? Gender, string sportname)
        {

            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(User.Identity.GetUserId());
            int memberID = user.MemberID;
            try
            {
                getSports();
                ViewBag.sports = sports;
                int sport_id = 0;
                for (int item = 0; item < sports.Count; item++)
                {
                    if (sports[item] == sportname)
                    {
                        sport_id = sportIds[item];
                    }
                }

                if (Gender != true) Gender = false;

                Team team = new Team()
                {
                    TeamName = TeamName,
                    Gender = Gender,
                    SportID = sport_id,
                    MemberID = memberID
                };

                int result = teamManager.AddTeam(team);
                if (result > 0)
                {
                    ViewBag.Message = "Team created successfully!";
                    ViewBag.Error = false;
                }
                else
                {
                    ViewBag.Message = "An error has occurred!";
                    ViewBag.Error = true;
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }

            return View();
        }

        private void getSports()
        {
            try
            {
                List<string> _sports = teamManager.getSportName();
                foreach (string line in _sports)
                {
                    // Add them into the listbox
                    sports.Add(line.Substring(5));
                    sportIds.Add(Int32.Parse(line.Substring(0, 4)));
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }
        }

        // GET: RetriveAllTeams
        /// <summary>
        /// /// Garion Opiola
        /// Created: 2023/04/08
        /// gets all teams for controller
        /// </summary>
        public ActionResult AllTeams()
        {
            try
            {
                teams = teamManager.RetrieveAllTeams();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex;
            }

            return View(teams);
        }

        // GET: Team Deactivate
        /// <summary>
        /// /// Garion Opiola
        /// Created: 2023/04/16
        /// deactivate team for WEB app
        /// </summary>
        public ActionResult Deactivate(int team_id)
        {
            int result = 0;
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.FindById(User.Identity.GetUserId());
            int memberID = user.MemberID;

            try
            {
                result = teamManager.RemoveOwnTeam(team_id, memberID);
                if (result > 0)
                {
                    ViewBag.Error = false;
                    ViewBag.Message = "Team deavtivated successfully!";
                }
                else
                {
                    ViewBag.Error = true;
                    ViewBag.Message = "An error has occurred!";
                }
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
            }

            return RedirectToAction("AllTeams", new
            {
                memberID = memberID,
            });
            return View();
        }
    }
}

Extremely Casual Game Organizer/MvcPresentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ECGO</title>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.Title == "Home Page")
                    {
                        <li class="current" style="height:100%">@Html.ActionLink("ECGO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("ECGO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    }
                    @if (ViewBag.Title == "Schedule")
                    {
                        <li class="current">@Html.ActionLink("View Schedule", "ViewSchedule", "Schedule")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("View Schedule", "ViewSchedule", "Schedule") </li>
                    }

                    <li class="nav-item dropdown">
                        @if (ViewBag.Title == "All Games")
                        {
                            <a href="#" class="navbar-link dropdown-toggle current" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Games</a>
                        }
                        else
                        {
                            <a href="#" class="navbar-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Games</a>
                        }
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("View All Games", "AllGames", "Games")</li>
                            <li>@Html.ActionLink("Create a Game", "CreateGame", "Games")</li>
                            <li>@Html.ActionLink("Manage My Games", "EditGames", "Games")</li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        @if (ViewBag.Title == "AllLeagues" || ViewBag.Title == "CreateLeague")
                        {
                            <a href="#" class="navbar-link dropdown-toggle current" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Leagues</a>
                        }
                        else
                        {
                            <a href="#" class="navbar-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Leagues</a>
                        }
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("View All Leagues", "AllLeagues", "League")</li>
                            <li>@Html.ActionLink("Create a League", "CreateLeague", "League")</li>
                            <li>@Html.ActionLink("Manage My Leagues", "AllLeagues", "League")</li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        @if (ViewBag.Title == "AllTournaments" || ViewBag.Title == "CreateTournament")
                        {
                            <a href="#" class="navbar-link dropdown-toggle current" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tournaments</a>
                        }
                        else
                        {
                            <a href="#" class="navbar-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tournaments</a>
                        }
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("View All Tournaments", "AllTournaments", "Tournaments")</li>
                            <li>@Html.ActionLink("My Tournaments", "MemberTournaments", "Tournaments")</li>
                            <li>@Html.ActionLink("Create a Tournament", "CreateTournament", "Tournaments")</li>
                            @*<li>@Html.ActionLink("Manage My Tournaments", "EditTournaments", "Tournaments")</li>*@
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        @if (ViewBag.Title == "All Teams" || ViewBag.Title == "Create")
                        {
                            <a href="#" class="navbar-link dropdown-toggle current" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Teams</a>
                        }
                        else
                        {
                            <a href="#" class="navbar-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Teams</a>
                        }
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("View All Teams", "AllTeams", "Teams")</li>
                            <li>@Html.ActionLink("My Teams", "MemberTeams", "Teams")</li>
                            <li>@Html.ActionLink("Create a Team", "CreateTeam", "Teams")</li>
                            <li>@Html.ActionLink("Manage My Teams", "EditTeams", "Teams")</li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        @if (ViewBag.Title == "Search")
                        {
                            <a href="#" class="navbar-link dropdown-toggle current" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search</a>
                        }
                        else
                        {
                            <a href="#" class="navbar-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search</a>
                        }
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Search", "Search", "Search")</li>
                        </ul>
                    </li>
                    @*
                        Michael Haring
                        05/01/2023
                        Only shows admin tab if member is signed in as admin
                    *@
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            @Html.ActionLink("Admin", "Index", "Admin", new { area = "" }, new { @class = "nav-link" })
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="main-div">
            @RenderBody()
        </div>

        <hr />

        <footer id="footer">
            <p>&copy; @DateTime.Now.Year - Extremely Casual Game Organizer</p>
        </footer>
    </div>

    @*This is a popup window for Message*@
    <div id="Message" style="display:flex;justify-content:end; width:700px; padding:20px">
        <div class="chat-popup" id="myForm" data-aos="slide-up">
            <div style="display:flex;justify-content:end; padding:0px 20px">
                <a href="" style="text-align:right" class="closeBtn" onclick="closeForm()">
                    <img src="~/Images/close.png"
                         alt="sms" class="img-fluid img-responsive text-center" width="40" />

                </a>
            </div>
            <div id="frame" style="border: 3px solid gray; overflow: hidden; margin:0px 15px 15px auto; max-width: 700px;">
                <iframe scrolling="no" src="@Url.Action("PeopleITexted","Messages")"
                        style="border: 0px none; height: 900px; max-height: 90vh; margin-top: -60px; width: 500px">
                </iframe>
            </div>
        </div>
        <div id="messageForDestop" style="padding:0px 10px; text-align:center">
            <button type="button" id="btnOpen" class="btn btn-info btn-lg" onclick="openForm()">
                <span style="display:flex;align-items:center; flex-direction:column;">
                    <img src="~/Images/sms.png"
                         alt="sms" class="img-fluid img-responsive text-center" width="50" />
                    @*Messages*@
                </span>
            </button>
        </div>
        <div id="messageForMobile" style="padding:0px 10px; text-align:center">
            <a href="~/Messages/PeopleITexted" type="button" id="btnOpenMobile" class="btn btn-info btn-lg">
                <span style="display:flex;align-items:center; flex-direction:column;">
                    <img src="~/Images/sms.png"
                         alt="sms" class="img-fluid img-responsive text-center" width="50" />
                    @*Messages*@
                </span>
            </a>
        </div>
    </div>
    @*Message popup window end*@


    @*@Scripts.Render("~/Content/App.js")*@
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    @Scripts.Render("~/Content/App.js")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>